### ISSUE TITLE
KeyError: 'ENVIRONMENTAL_VARIABLES'

### ISSUE THREAD

**Issue by gongxq19** [MolecularAI/ReinventCommunity#26]
Hi,
When I run python input.py some_running_mode.json, an error happened.
Traceback (most recent call last):
  File "/home/cuda/Desktop/Reinvent-master/Reinvent-master/input.py", line 20, in <module>
    manager = Manager(configuration)
  File "/home/cuda/Desktop/Reinvent-master/Reinvent-master/running_modes/manager.py", line 13, in __init__
    self._load_environmental_variables()
  File "/home/cuda/Desktop/Reinvent-master/Reinvent-master/running_modes/manager.py", line 30, in _load_environmental_variables
    raise ex
  File "/home/cuda/Desktop/Reinvent-master/Reinvent-master/running_modes/manager.py", line 24, in _load_environmental_variables
    environmental_variables = config["ENVIRONMENTAL_VARIABLES"] 
KeyError: 'ENVIRONMENTAL_VARIABLES'
Thanks, looking forward to your advice!

**Comment by GuoJeff** [comment]
Hi @gongxq19,

Sorry for the delay. Can you try running again with the latest code? There are new `Reinvent` and `ReinventCommunity` versions recently released.

**Comment by pmaen** [comment]
I was just able to reproduce the error when using the [Complete_Use-Case-DRD2_Demo.ipynb](https://github.com/MolecularAI/ReinventCommunity/blob/master/notebooks/Complete_Use-Case-DRD2_Demo.ipynb) notebook.
Is there any way to fix this since it makes the entire program unusable?

edit: I just installed everything yesterday according to the instructions, hence it's the newest version of everything.
